import {useState,useEffect,useCallback,useRef} from 'react';
import {ApiClient, type Leaderboard} from '@focus/client';
import type {Dashboard,Round} from '@focus/core';
import {Button,Icon,fmt,type IconName} from './ui';
import {Timer,Stats,Profile,Rating} from './screens';
import {Games} from './games';
const api=new ApiClient();
const nav:{id:IconName;label:string}[]=[{id:'timer',label:'Таймер'},{id:'stats',label:'Статистика'},{id:'games',label:'Игры'},{id:'rating',label:'Рейтинг'},{id:'profile',label:'Профиль'}];
export function App(){
  const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[authenticated,setAuthenticated]=useState(false),[page,setPage]=useState<IconName>((location.hash.slice(1) as IconName)||'timer'),[theme,setTheme]=useState(localStorage.getItem('fc-theme')??'dark'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(navigator.onLine),[clock,setClock]=useState(Date.now()),[rank,setRank]=useState<Leaderboard|null>(null),[game,setGame]=useState(''),[result,setResult]=useState<Round|null>(null);
  const offset=useRef(0),mounted=useRef(true),lastActive=useRef<string|null>(null);
  const refresh=useCallback(async()=>{const d=await api.dashboard();offset.current=Date.parse(d.serverTime)-Date.now();setData(d);setOnline(true);if(lastActive.current&&!d.active){const s=d.history.find(s=>s.id===lastActive.current);if(s?.status==='completed')setNotice(`Сессия завершена. Начислено ${fmt(s.reward)} монет.`);}lastActive.current=d.active?.id??null;return d;},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('fc-theme',theme);},[theme]);
  useEffect(()=>{mounted.current=true;api.restore().then(()=>{if(mounted.current){setAuthenticated(true);return refresh();}}).catch(()=>{}).finally(()=>{if(mounted.current)setLoading(false);});return()=>{mounted.current=false;};},[refresh]);
  useEffect(()=>{const id=setInterval(()=>setClock(Date.now()+offset.current),1000);return()=>clearInterval(id);},[]);
  useEffect(()=>{if(!authenticated)return;const poll=()=>{if(document.visibilityState==='visible')refresh().catch(()=>setOnline(false));},id=setInterval(poll,5000);const resume=()=>{setOnline(navigator.onLine);poll();};window.addEventListener('online',resume);window.addEventListener('offline',resume);document.addEventListener('visibilitychange',poll);return()=>{clearInterval(id);window.removeEventListener('online',resume);window.removeEventListener('offline',resume);document.removeEventListener('visibilitychange',poll);};},[authenticated,refresh]);
  useEffect(()=>{if(!authenticated)return;const track=()=>api.visit().catch(()=>{});track();const activity=()=>{const t=Date.now();if(t-visitTime.current>60000){visitTime.current=t;track();}};window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);return()=>{window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);};},[authenticated]);
  const visitTime=useRef(Date.now());
  const run=async<T,>(work:()=>Promise<T>):Promise<T|undefined>=>{if(busy)return;setBusy(true);setError('');try{const r=await work();await refresh();return r;}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const go=(id:IconName)=>{setPage(id);location.hash=id;setError('');setGame('');setResult(null);};
  useEffect(()=>{const hash=()=>{const id=location.hash.slice(1) as IconName;if(nav.some(n=>n.id===id))setPage(id);};window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash);},[]);
  useEffect(()=>{if(page==='rating'&&authenticated)api.leaderboard().then(setRank).catch(e=>setError(e.message));},[page,authenticated,data?.balance]);
  const auth=async(login:string,password:string,nickname?:string)=>{setBusy(true);setError('');try{if(nickname)await api.register(login,nickname,password);else await api.login(login,password);setAuthenticated(true);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(loading)return <div className="loading">Focus Coins · подключение…</div>;
  if(!authenticated||!data)return <AuthScreen auth={auth} busy={busy} error={error}/>;
  const light=theme==='light',season=new Date(`${data.season.key}-15T12:00:00Z`).toLocaleDateString('ru-RU',{month:'long',year:'numeric'}),days=Math.max(0,Math.ceil((Date.parse(data.season.endsAt)-clock)/86400_000));
  const title={coin:['',''],timer:['Время для главного','Одна задача. Один таймер. Каждая минута приносит монету.'],stats:['Каждая минута имеет значение','Ваша концентрация, серия дней и движение монет.'],games:[game==='roulette'?'Рулетка':game==='wheel'?'Колесо фортуны':game==='tower'?'Башня':'Монеты в игре',game?'Одна ставка. Решение за вами.':'Три способа испытать удачу после хорошей работы.'],rating:['Один месяц. Новый старт.','Рейтинг по балансу: концентрация, бонусы и результаты игр.'],profile:['Ваше место в Focus Coins','Настройки аккаунта, уведомлений и внешнего вида.']}[page]??['Время для главного',''];
  return <div className="app"><header className="app-header"><Icon name="coin" size={36}/><div className="brand"><b>Focus Coins</b><small>ВРЕМЯ, КОТОРОЕ ОСТАЁТСЯ</small></div><div className="header-spacer"/><span className="badge">● {online?'Синхронизировано':'Нет связи'}</span><Button onClick={()=>go('profile')}>{data.user.nickname}</Button><span className="mobile-balance">{fmt(data.balance)}</span></header><div className="workspace"><aside className="sidebar"><small>МОЙ ФОКУС</small><nav>{nav.map(n=><button key={n.id} className={`nav-item ${page===n.id?'active':''}`} onClick={()=>go(n.id)}><Icon name={n.id} light={light} active={page===n.id}/>{n.label}</button>)}</nav><div className="sidebar-spacer"/><div className="wallet inset"><small>БАЛАНС СЕЗОНА</small><b><Icon name="coin" size={22}/>{fmt(data.balance)}</b><small>Виртуальные монеты</small></div><div className="season-info"><b>{season}</b><span className="mint">Место № {data.rank}</span><small>До нового сезона: {days} дн.</small></div></aside><main><div className="page-title"><div><h1>{title[0]}</h1><p>{title[1]}</p></div>{game?<Button onClick={()=>{setGame('');setResult(null);}}>← Все игры</Button>:<span className="badge">{new Date(clock).toLocaleDateString('ru-RU',{timeZone:'Asia/Yekaterinburg',day:'2-digit',month:'long',weekday:'long'})}</span>}</div>{error&&<div className="message error" role="alert">{error}<button aria-label="Закрыть ошибку" onClick={()=>setError('')}>×</button></div>}{notice&&<div className="message" role="status">{notice}<button aria-label="Закрыть уведомление" onClick={()=>setNotice('')}>×</button></div>}{!online&&<div className="message">Нет соединения. Запущенная сессия продолжает идти. Состояние обновится после подключения.</div>}
  {page==='timer'&&<Timer data={data} clock={clock} busy={busy||!online} start={m=>run(()=>api.start(m,crypto.randomUUID()))} cancel={()=>run(()=>api.cancel(data.active!.id,crypto.randomUUID()))}/>}
  {page==='stats'&&<Stats data={data}/>}
  {page==='games'&&<Games data={data} game={game} setGame={setGame} busy={busy||!online} result={result} play={async(kind,stake,bet)=>{const r=await run(()=>api.play(kind,stake,crypto.randomUUID(),bet));if(r)setResult(r);return r;}} pick={async cell=>{const r=await run(()=>api.pick(data.tower!.id,cell,crypto.randomUUID()));if(r)setResult(r);}} collect={async()=>{const r=await run(()=>api.collect(data.tower!.id,crypto.randomUUID()));if(r)setResult(r);}}/>}
  {page==='rating'&&<Rating data={data} rank={rank} days={days} load={key=>api.leaderboard(key).then(setRank).catch(e=>setError(e.message))}/>}
  {page==='profile'&&<Profile data={data} theme={theme} setTheme={setTheme} busy={busy} save={async nickname=>{await run(()=>api.profile(nickname));}} changePassword={async(current,next)=>{await run(()=>api.password(current,next));}} logout={async()=>{try{await api.logout();setAuthenticated(false);setData(null);}catch(e){setError((e as Error).message);}}}/>}
  </main></div><footer><span className="mint">● {online?'Онлайн':'Нет связи'}</span><span>Сезон: {season}</span><span>Asia/Yekaterinburg · UTC+5</span></footer><nav className="mobile-nav">{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>go(n.id)}><Icon name={n.id} light={light} active={page===n.id}/>{n.label}</button>)}</nav></div>;
}
function AuthScreen({auth,busy,error}:{auth:(login:string,password:string,nickname?:string)=>void;busy:boolean;error:string}){const [register,setRegister]=useState(false),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[nickname,setNickname]=useState('');return <div className="auth"><div className="auth-art"><div className="auth-brand"><Icon name="coin" size={32}/><b>Focus Coins</b></div><div className="auth-hero"><h1>Ваше время<br/>становится ценным.</h1><p>Концентрируйтесь. Собирайте монеты.<br/>Начинайте каждый месяц с нового рекорда.</p><div className="auth-clock inset"><strong>25:00</strong><small>25 минут → 25 монет</small></div><div className="auth-features">{(['timer','coin','rating'] as IconName[]).map((n,i)=><div key={n}><Icon name={n} active/><small>{['Таймер','Монеты','Сезоны'][i]}</small></div>)}</div></div><small>Небольшие шаги. Каждый день.</small></div><div className="auth-form-wrap"><form className="auth-form bevel" onSubmit={e=>{e.preventDefault();auth(login,password,register?nickname:undefined);}}><h1>{register?'Начните свою историю':'С возвращением'}</h1><p>{register?'Один аккаунт для компьютера и телефона.':'Ваш фокус уже ждёт вас.'}</p><div className="row"><Button type="button" selected={!register} onClick={()=>setRegister(false)}>Вход</Button><Button type="button" selected={register} onClick={()=>setRegister(true)}>Регистрация</Button></div><label>Логин<input autoComplete="username" required minLength={3} maxLength={32} value={login} onChange={e=>setLogin(e.target.value)} placeholder="anna_focus" pattern="[a-zA-Z0-9_.-]+"/></label>{register&&<label>Никнейм<input required minLength={3} maxLength={24} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="pixel_anna"/></label>}<label>Пароль<input type="password" autoComplete={register?'new-password':'current-password'} required minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error-text" role="alert">{error}</p>}<Button primary disabled={busy}>{busy?'Подключение…':register?'Создать аккаунт':'Войти'}</Button><small>Монеты виртуальные: покупка и вывод недоступны.</small></form></div></div>;}

