import React,{useState,useEffect,useRef} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,AppState,Alert,Image} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {NativeIcon,gameImages} from './assets';
import {NativeWheel} from './NativeWheel';
import {useFonts} from 'expo-font';
import {PTSans_400Regular} from '@expo-google-fonts/pt-sans/400Regular';
import {PTSans_700Bold} from '@expo-google-fonts/pt-sans/700Bold';
import {IBMPlexMono_500Medium} from '@expo-google-fonts/ibm-plex-mono/500Medium';
import {StatusBar} from 'expo-status-bar';
import * as SecureStore from 'expo-secure-store';
import * as Notifications from 'expo-notifications';
import * as Crypto from 'expo-crypto';
import {ApiClient,type Leaderboard} from '@focus/client';
import {WHEEL,DAILY_REWARDS,towerPayout,cents,type Dashboard,type RouletteBet,type Round} from '@focus/core';
const api=new ApiClient(process.env.EXPO_PUBLIC_API_URL??'http://10.0.2.2:3000/api/v1',{get:()=>SecureStore.getItemAsync('fc-refresh'),set:async t=>{if(t)await SecureStore.setItemAsync('fc-refresh',t);else await SecureStore.deleteItemAsync('fc-refresh');}});
Notifications.setNotificationHandler({handleNotification:async()=>({shouldPlaySound:true,shouldSetBadge:false,shouldShowBanner:true,shouldShowList:true})});
const fmt=(n:string|number)=>Number(n).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2});
const nav=['Таймер','Статистика','Игры','Рейтинг','Профиль'];
const gameNames={roulette:'Рулетка',wheel:'Колесо фортуны',tower:'Башня'};
const dark={bg:'#18232c',panel:'#2c3943',inset:'#101d24',text:'#f0f3eb',muted:'#acbac1',mint:'#9ee7c5',gold:'#f4cf70',edge:'#7d909c',shadow:'#09131c'},light={bg:'#ece9e2',panel:'#d4d0c8',inset:'#f7f7f0',text:'#17232e',muted:'#505a62',mint:'#166850',gold:'#7b570d',edge:'#fff',shadow:'#767970'};
export default function App(){
 const scroll=useRef<ScrollView>(null);
 const [preferencesLoaded,setPreferencesLoaded]=useState(false);
 const [fontsLoaded]=useFonts({PTSans_400Regular,PTSans_700Bold,IBMPlexMono_500Medium});
 const [d,setD]=useState<Dashboard|null>(null),[page,setPage]=useState(0),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[nickname,setNickname]=useState(''),[register,setRegister]=useState(false),[busy,setBusy]=useState(false),[spinning,setSpinning]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(Date.now()),[minutes,setMinutes]=useState('25'),[game,setGame]=useState(''),[stake,setStake]=useState('1'),[bet,setBet]=useState<RouletteBet>({type:'black'}),[result,setResult]=useState<Round|null>(null),[rating,setRating]=useState<Leaderboard|null>(null),[theme,setTheme]=useState('dark'),[notifications,setNotifications]=useState(true),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[search,setSearch]=useState('');
 const colors=theme==='light'?light:dark,offset=useRef(0),notificationSession=useRef<string|null>(null),notificationId=useRef<string|null>(null),syncing=useRef(false),lastActivity=useRef(0);
 async function sync(){if(syncing.current)return;syncing.current=true;try{const next=await api.dashboard();offset.current=Date.parse(next.serverTime)-Date.now();setD(next);setError(e=>e==="Нет связи. Таймер продолжает идти."?"":e);setNickname(v=>v||next.user.nickname);if(next.active?.id!==notificationSession.current){notificationSession.current=next.active?.id??null;if(notificationId.current)await Notifications.cancelScheduledNotificationAsync(notificationId.current);notificationId.current=null;if(next.active&&notifications){try{await Notifications.setNotificationChannelAsync('focus',{name:'Сессии концентрации',importance:Notifications.AndroidImportance.HIGH});const permission=await Notifications.requestPermissionsAsync();if(permission.granted&&Date.parse(next.active.endsAt)>Date.now()+offset.current)notificationId.current=await Notifications.scheduleNotificationAsync({content:{title:'Focus Coins',body:'Сессия завершена. Монеты начислит сервер.',sound:'default'},trigger:{type:Notifications.SchedulableTriggerInputTypes.DATE,date:new Date(Date.parse(next.active.endsAt)-offset.current),channelId:'focus'}});}catch{ /* Notification permission never affects rewards. */ }}}return next;}finally{syncing.current=false;}}
 async function run(work:()=>Promise<unknown>){if(busy||spinning)return;setBusy(true);setError('');try{await work();if(api.accessToken)await sync();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{Promise.all([SecureStore.getItemAsync('fc-theme'),SecureStore.getItemAsync('fc-notifications')]).then(([t,n])=>{if(t)setTheme(t);setNotifications(n!=='off');}).catch(()=>{}).finally(()=>setPreferencesLoaded(true));},[]);
 useEffect(()=>{if(preferencesLoaded)api.restore().then(sync).catch(()=>{});},[preferencesLoaded]);
 useEffect(()=>{const tick=setInterval(()=>setClock(Date.now()+offset.current),1000);return()=>clearInterval(tick);},[]);
 useEffect(()=>{if(!d)return;const poll=setInterval(()=>{if(AppState.currentState==='active')sync().catch(()=>setError('Нет связи. Таймер продолжает идти.'));},5000),resume=AppState.addEventListener('change',s=>{if(s==='active')sync().catch(()=>{});});return()=>{clearInterval(poll);resume.remove();};},[d?.user.id,notifications]);
 useEffect(()=>{if(page===3&&d)api.leaderboard().then(setRating).catch(e=>setError(e.message));},[page,d?.balance]);
 useEffect(()=>{setSpinning(false);setResult(null);scroll.current?.scrollTo({y:0,animated:false});},[page,game]);
 const activity=()=>{if(d&&Date.now()-lastActivity.current>60000){lastActivity.current=Date.now();api.visit().catch(()=>{});}};
 const button=(label:string,action:()=>void,primary=false,disabled=false)=><Pressable accessibilityRole="button" onPress={()=>{activity();action();}} disabled={busy||spinning||disabled} style={({pressed})=>[styles.button,{backgroundColor:primary?'#12388e':colors.panel,borderTopColor:pressed?colors.shadow:colors.edge,borderLeftColor:pressed?colors.shadow:colors.edge,borderBottomColor:pressed?colors.edge:colors.shadow,borderRightColor:pressed?colors.edge:colors.shadow,opacity:(busy||spinning||disabled)?0.55:1}]}><Text style={{color:primary?'#fff':colors.text,fontWeight:'700',textAlign:'center',fontFamily:'PTSans_700Bold'}}>{label}</Text></Pressable>;
 const field=(label:string,value:string,set:(v:string)=>void,secret=false,numeric=false)=><View style={styles.field}><Text style={{color:colors.muted,fontFamily:'PTSans_400Regular'}}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={set} secureTextEntry={secret} keyboardType={numeric?'numeric':'default'} autoCapitalize="none" style={[styles.input,{backgroundColor:colors.inset,color:colors.text,borderBottomColor:colors.edge,borderRightColor:colors.edge}]}/></View>;
 const panel=(title:string,children:React.ReactNode)=><View style={[styles.panel,{backgroundColor:colors.panel,borderTopColor:colors.edge,borderLeftColor:colors.edge,borderBottomColor:colors.shadow,borderRightColor:colors.shadow}]}><Text style={styles.panelTitle}>{title}</Text><View style={styles.body}>{children}</View></View>;
 const text=(s:string,color=colors.text)=><Text style={{color,lineHeight:22,fontFamily:'PTSans_400Regular'}}>{s}</Text>;
 const active=d?.active,left=active?Math.max(0,Math.ceil((Date.parse(active.endsAt)-clock)/1000)):Number(minutes||0)*60,clockLabel=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;
 const roundHistory=(r:Round)=><View key={r.id} style={{gap:6,paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.edge}}>{text(gameNames[r.kind as keyof typeof gameNames]??'Игра',colors.mint)}{r.kind==='roulette'&&text(`Выпало число ${r.result.number}`)}{r.kind==='wheel'&&text(`Множитель ×${r.result.multiplier}`)}{[['Ставка',r.stake],['Выплата',r.payout],['Чистый результат',r.net]].map(([label,value])=><View key={label} style={{flexDirection:'row',gap:8,alignItems:'flex-start'}}><Text style={{flex:1,minWidth:0,color:colors.muted,lineHeight:22,fontFamily:'PTSans_400Regular'}}>{label}</Text><Text style={{flexShrink:0,textAlign:'right',color:colors.gold,lineHeight:22,fontFamily:'PTSans_400Regular'}}>{fmt(value)}</Text></View>)}</View>;
 const play=()=>run(async()=>{setResult(null);setSpinning(game!=='tower');try{setResult(await api.play(game,stake,Crypto.randomUUID(),game==='roulette'?bet:undefined));}catch(e){setSpinning(false);throw e;}});
 const tower=d?.tower??(game==='tower'&&result?.kind==='tower'?d?.rounds.find(r=>r.id===result.id)??result:null);
 const displayedResult=game==='tower'?tower:result;
 if(!fontsLoaded)return <SafeAreaProvider><SafeAreaView style={{flex:1,backgroundColor:colors.bg,justifyContent:'center',alignItems:'center'}}><Text style={{color:colors.text}}>Focus Coins…</Text></SafeAreaView></SafeAreaProvider>;
 return <SafeAreaProvider><SafeAreaView style={[styles.safe,{backgroundColor:colors.bg}]}><StatusBar style={theme==='light'?'dark':'light'}/><View style={styles.header}><View style={[styles.row,{flex:1,minWidth:0}]}><NativeIcon name="coin" size={32}/><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.75} style={styles.brand}>Focus Coins</Text></View>{d&&<Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.65} style={styles.headerBalance}>{fmt(d.balance)}</Text>}</View><ScrollView ref={scroll} contentContainerStyle={styles.content} onTouchStart={activity} keyboardShouldPersistTaps="handled">{error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}
 {!d?panel(register?'НАЧНИТЕ СВОЮ ИСТОРИЮ':'С ВОЗВРАЩЕНИЕМ',<>{text('Один аккаунт для компьютера и телефона.')}{field('Логин',login,setLogin)}{register&&field('Никнейм',nickname,setNickname)}{field('Пароль',password,setPassword,true)}{button(busy?'Подключение…':register?'Создать аккаунт':'Войти',()=>run(async()=>{if(register)await api.register(login,nickname,password);else await api.login(login,password);await api.visit();}),true)}{button(register?'Уже есть аккаунт':'Регистрация',()=>setRegister(!register))}{text('Монеты виртуальные. Покупка и вывод недоступны.',colors.muted)}</>):<>
 <Text style={[styles.heading,{color:colors.text}]}>{page===0?'Время для главного':nav[page]}</Text>
 {page===0&&<>{panel('КОНЦЕНТРАЦИЯ',<><View style={[styles.timer,{backgroundColor:colors.inset}]}>{text(active?'СЕССИЯ ИДЁТ':'ГОТОВЫ НАЧАТЬ?',colors.mint)}<Text adjustsFontSizeToFit minimumFontScale={0.65} numberOfLines={1} style={[styles.clock,{color:colors.mint}]}>{clockLabel}</Text>{text(`+${active?active.minutes*active.multiplier:Number(minutes)} монет за сессию`,colors.muted)}</View>{active?button('Отменить сессию',()=>Alert.alert('Отменить сессию?','Монеты не будут начислены.',[{text:'Продолжить',style:'cancel'},{text:'Отменить',style:'destructive',onPress:()=>run(()=>api.cancel(active.id,Crypto.randomUUID()))}])):<><View style={styles.row}>{[25,50,90].map(m=><View key={m} style={styles.flex}>{button(String(m),()=>setMinutes(String(m)))}</View>)}</View>{field('Своя длительность · 1–360 минут',minutes,setMinutes,false,true)}{button('Начать сессию',()=>run(()=>api.start(Number(minutes),Crypto.randomUUID())),true,!Number.isInteger(Number(minutes))||Number(minutes)<1||Number(minutes)>360)}</>}{text('Таймер продолжит идти после закрытия приложения.',colors.muted)}</>)}{panel('ЕЖЕДНЕВНАЯ ЦЕЛЬ',<>{text(`${d.daily.streak} дней подряд`,colors.mint)}{text(`Сегодня ${d.daily.minutes} / 25 минут`)}<View style={styles.row}>{DAILY_REWARDS.map((r,i)=><View key={r} style={[styles.day,{backgroundColor:i+1===d.daily.cycle?'#12388e':colors.inset}]}><Text style={{color:i+1===d.daily.cycle?'#fff':colors.text,textAlign:'center'}}>{i+1}</Text><Text style={{color:i+1===d.daily.cycle?'#fff':colors.gold,textAlign:'center',fontSize:11}}>+{r}</Text></View>)}</View>{text(d.daily.awarded?'Бонус начислен автоматически.':`Ещё ${Math.max(0,25-d.daily.minutes)} минут → бонус +${DAILY_REWARDS[d.daily.cycle-1]}`,colors.gold)}{text('На 7-й день: +50 монет и ×1,5 на 24 часа.')}{text('День считается по окончанию сессии · UTC+5',colors.muted)}</>)}{panel('ПОСЛЕДНИЕ СЕССИИ',<>{d.history.length?d.history.slice(0,10).map(s=><View key={s.id} style={styles.listRow}>{text(`${s.minutes} мин · ${s.status==='completed'?'Завершена':s.status==='active'?'Идёт':'Отменена'}`)}{text(`+${fmt(s.reward)}`,colors.gold)}</View>):text('Начните первую сессию.')}</>)}</>}
 {page===1&&<>{panel('ВАША КОНЦЕНТРАЦИЯ',<>{text(`Всего: ${d.stats.totalMinutes} минут`)}{text(`За неделю: ${d.stats.weekMinutes} минут`)}{text(`За месяц: ${d.stats.monthMinutes} минут`)}{text(`Завершено: ${d.stats.completed} · отменено: ${d.stats.cancelled}`)}{d.stats.days.slice(-7).map(day=><View key={day.day} style={styles.listRow}>{text(day.day.slice(5))}{text(`${day.minutes} мин`,colors.mint)}</View>)}</>)}{panel('МОНЕТЫ В СЕЗОНЕ',<>{text(`Концентрация: ${fmt(d.stats.focusCoins)}`,colors.mint)}{text(`Бонусы: ${fmt(d.stats.bonusCoins)}`,colors.gold)}{text(`Игры: ${fmt(d.stats.gameNet)}`)}</>)}</>}
 {page===2&&<>{!game?<>{['roulette','wheel','tower'].map((g,i)=>panel(['РУЛЕТКА','КОЛЕСО ФОРТУНЫ','БАШНЯ'][i],<><Image source={gameImages[g as keyof typeof gameImages]} style={{width:"100%",height:180}} resizeMode="contain"/>{text(['37 чисел · цвет, чётность или число','5 исходов · от ×0 до ×15','8 этажей · 3 безопасные клетки из 4'][i])}{button('Открыть игру',()=>{setGame(g);setResult(null);})}</>))}</>:<>{button('← Все игры',()=>setGame(''))}{panel(game==='roulette'?'РУЛЕТКА':game==='wheel'?'КОЛЕСО ФОРТУНЫ':'БАШНЯ',<>{(game==='roulette'||game==='wheel')&&<NativeWheel kind={game} result={result} onComplete={()=>setSpinning(false)}/>}
 {game==='tower'&&<View style={{gap:6}}>{Array.from({length:8},(_,i)=>8-i).map(floor=><View key={floor} style={styles.row}><Text style={{color:colors.muted,width:18,textAlign:'center'}}>{floor}</Text>{[0,1,2,3].map(cell=>{const chosen=tower?.picks[floor-1]===cell,safe=chosen&&floor<=tower!.floors,lost=chosen&&tower?.status==='lost'&&floor===tower.floors+1;return <Pressable key={cell} accessibilityRole="button" accessibilityLabel={`${floor}-й этаж, клетка ${cell+1}`} disabled={busy||!tower||tower.status!=='active'||floor!==tower.floors+1} onPress={()=>run(async()=>setResult(await api.pick(tower!.id,cell,Crypto.randomUUID())))} style={{flex:1,minHeight:38,alignItems:'center',justifyContent:'center',backgroundColor:safe?'#236649':lost?'#9b3735':colors.inset,borderWidth:1,borderColor:colors.edge}}><Text style={{color:safe||lost?'#f0f3eb':colors.text}}>{safe?'✓':lost?'×':tower?.status==='active'&&floor===tower.floors+1?'?':'−'}</Text></Pressable>;})}<Text style={{color:colors.gold,width:36,fontSize:10,textAlign:'right'}}>×{(Number(towerPayout(10000n,floor))/10000).toFixed(2)}</Text></View>)}</View>}
 {game==='tower'&&tower?.status==='active'?<>{text(`Пройдено ${tower.floors} / 8 этажей`)}{text(`Можно забрать ${fmt(Number(towerPayout(cents(tower.stake),tower.floors))/100)}`,colors.gold)}{button('Забрать выигрыш',()=>run(async()=>setResult(await api.collect(tower.id,Crypto.randomUUID()))),true,!tower.floors)}{text('Автозабор через 15 минут бездействия.')}</>:<>{field(`Ставка · доступно ${fmt(d.balance)}`,stake,setStake,false,true)}{button('Всё',()=>setStake(d.balance))}{game==='roulette'&&<><View style={[styles.row,{flexWrap:'wrap'}]}>{(['red','black','even','odd','number'] as const).map((t,i)=><View key={t} style={{flexBasis:'47%',flexGrow:1}}>{button(['Красное','Чёрное','Чётное','Нечётное','Число'][i],()=>setBet({type:t,number:0}),bet.type===t)}</View>)}</View>{bet.type==='number'&&field('Число 0–36',String(bet.number??0),v=>setBet({type:'number',number:Number(v)}),false,true)}{text(bet.type==='number'?'Шанс 1/37 · выплата ×36':'Шанс 18/37 · выплата ×2')}</>}{game==='wheel'&&WHEEL.map(s=>text(`${s.chance}% · ×${s.multiplier} · ${fmt(Number(stake)*s.multiplier)}`))}{button(game==='tower'?'Начать раунд':spinning?'Вращение…':'Крутить',play,true,Number(stake)<1||Number(stake)>Number(d.balance)||!Number.isFinite(Number(stake)))}</>}<View accessibilityLiveRegion="polite" style={{minHeight:72,justifyContent:'center'}}>{spinning?text(result?'Колесо вращается…':'Подключение…',colors.muted):displayedResult?text(displayedResult.status==='active'?displayedResult.floors?'Безопасно!':'Выберите клетку первого этажа.':`Выплата ${fmt(displayedResult.payout)} · результат ${fmt(displayedResult.net)}`,colors.mint):text('Результат появится здесь.',colors.muted)}</View>{text('Все множители включают возврат ставки.',colors.muted)}</>)}</>}{panel('ИСТОРИЯ ИГР',<>{d.rounds.filter(r=>r.status!=='active').slice(0,20).map(roundHistory)}</>)}</>}
 {page===3&&panel(`РЕЙТИНГ · ${rating?.season??d.season.key}`,<>{text(`Ваше место: № ${rating?.self?.rank??d.rank}`)}{field('Поиск по никнейму',search,setSearch)}{button('Текущий сезон',()=>api.leaderboard().then(setRating))}{rating?.archives.map(k=>button(k,()=>api.leaderboard(k).then(setRating)))}{rating?.rows.filter(r=>r.nickname.toLowerCase().includes(search.toLowerCase())).map(r=><View key={r.userId} style={{flexDirection:'row',gap:8,paddingVertical:8,alignItems:'flex-start'}}><Text style={{flex:1,minWidth:0,color:r.userId===d.user.id?colors.mint:colors.text,lineHeight:22,fontFamily:'PTSans_400Regular'}}>{`№ ${r.rank} · ${r.nickname}`}</Text><Text style={{flexShrink:0,textAlign:'right',color:colors.gold,lineHeight:22,fontFamily:'PTSans_400Regular'}}>{fmt(r.balance)}</Text></View>)}{text('Новый месяц — новый кошелёк. История и серия сохраняются.',colors.muted)}</>)}
 {page===4&&<>{panel('АККАУНТ',<>{text(`Логин: ${d.user.login}`)}{field('Никнейм',nickname,setNickname)}{button('Сохранить',()=>run(()=>api.profile(nickname)),true)}{field('Текущий пароль',currentPassword,setCurrentPassword,true)}{field('Новый пароль',newPassword,setNewPassword,true)}{button('Обновить пароль',()=>run(async()=>{await api.password(currentPassword,newPassword);setCurrentPassword('');setNewPassword('');}))}</>)}{panel('ПРЕДПОЧТЕНИЯ',<>{button(theme==='dark'?'Включить светлую тему':'Включить тёмную тему',()=>{const t=theme==='dark'?'light':'dark';setTheme(t);SecureStore.setItemAsync('fc-theme',t);})}{button(notifications?'Уведомления: включены':'Уведомления: выключены',()=>{setNotifications(!notifications);notificationSession.current=null;SecureStore.setItemAsync('fc-notifications',notifications?'off':'on');if(notifications&&notificationId.current)Notifications.cancelScheduledNotificationAsync(notificationId.current);})}{text('Asia/Yekaterinburg · UTC+5',colors.muted)}{button('Выйти из аккаунта',()=>run(async()=>{await api.logout();if(notificationId.current)await Notifications.cancelScheduledNotificationAsync(notificationId.current);setD(null);setNickname('');setPassword('');setLogin('');setGame('');setPage(0);}))}</>)}</>}
 </>}</ScrollView>{d&&<View style={[styles.nav,{backgroundColor:colors.panel}]}>{nav.map((n,i)=><Pressable key={n} onPress={()=>{activity();setPage(i);}} style={[styles.navItem,page===i&&{backgroundColor:'#12388e'}]}><NativeIcon name={(['timer','stats','games','rating','profile'] as const)[i]} active={page===i} light={theme==='light'}/><Text style={{fontFamily:'PTSans_400Regular',color:page===i?'#fff':colors.text,fontSize:10,textAlign:'center'}}>{n}</Text></Pressable>)}</View>}</SafeAreaView></SafeAreaProvider>;
}
const styles=StyleSheet.create({safe:{flex:1},header:{height:72,backgroundColor:'#c3cbcd',paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{flexShrink:1,fontSize:22,fontWeight:'700',fontFamily:'PTSans_700Bold',color:'#14232b'},headerBalance:{color:'#14232b',fontSize:14,maxWidth:'40%',flexShrink:1,textAlign:'right',marginLeft:12},content:{padding:16,gap:16,paddingBottom:24},heading:{fontSize:24,fontWeight:'700',fontFamily:'PTSans_700Bold'},panel:{borderTopWidth:1,borderLeftWidth:1,borderBottomWidth:2,borderRightWidth:2},panelTitle:{fontFamily:'PTSans_700Bold',backgroundColor:'#12388e',color:'#fff',fontSize:16,fontWeight:'700',padding:8},body:{padding:12,gap:12},row:{flexDirection:'row',gap:6,alignItems:'center'},flex:{flex:1},button:{minHeight:44,padding:10,borderTopWidth:1,borderLeftWidth:1,borderBottomWidth:2,borderRightWidth:2,justifyContent:'center'},input:{fontFamily:'PTSans_400Regular',minHeight:48,padding:12,borderBottomWidth:2,borderRightWidth:2},field:{gap:8},timer:{padding:16,alignItems:'center',gap:8},clock:{width:'100%',textAlign:'center',fontSize:64,fontWeight:'500',fontVariant:['tabular-nums'],fontFamily:'IBMPlexMono_500Medium'},day:{flex:1,paddingVertical:8},listRow:{flexDirection:'row',justifyContent:'space-between',gap:8,paddingVertical:8,flexWrap:'wrap'},error:{color:'#ed9992',backgroundColor:'#101d24',padding:12},nav:{height:68,flexDirection:'row'},navItem:{flex:1,alignItems:'center',justifyContent:'center'}});

