const kit=await figma.getNodeByIdAsync(state.kit);let cell=figma.currentPage.findOne(n=>n.type==='COMPONENT'&&n.name==='Game Cell');if(!cell){cell=keep(figma.createComponent());kit.appendChild(cell);cell.name='Game Cell';cell.description='Число рулетки или закрытая клетка башни. Label задаёт символ, размер переопределяется в экземпляре.';cell.resize(48,34);cell.layoutMode='HORIZONTAL';cell.primaryAxisSizingMode='FIXED';cell.counterAxisSizingMode='FIXED';cell.primaryAxisAlignItems='CENTER';cell.counterAxisAlignItems='CENTER';cell.fills=[paint('raised')];cell.x=650;cell.y=316;bevel(cell);const t=txt(cell,'?','Mono');t.componentPropertyReferences={characters:cell.addComponentProperty('Label','TEXT','?')};}
function gameCell(p,label,w,h,color='raised'){const n=instance(p,cell,w,h);prop(n,'Label',label);n.fills=[paint(color)];return n;}
function quickStake(p,w=336){const r=row(p,'Быстрая ставка',w,32,8);button(r,'½',72,'Secondary',null,32);button(r,'×2',72,'Secondary',null,32);button(r,'Всё',72,'Secondary',null,32);txt(r,'монет','Caption','muted');}
function gameFooter(content,title,desc){const n=frame(content,title,1168,116,'inset','VERTICAL',16,8);txt(n,title,'Label');txt(n,desc,'Small','muted',1136);txt(n,'Монеты виртуальные. Все множители включают возврат ставки.','Caption','muted');}
const screens=[];
{
const {root,content}=await shell('roulette','games','Рулетка','Европейское колесо: 0–36. Одна ставка на вращение.','← Все игры');route(root.findOne(n=>n.name==='Название раздела').children.at(-1),'games');screens.push(root);
const game=row(content,'Поле и ставка',1168,560,24);game.counterAxisAlignItems='MIN';const board=panel(game,'ЕВРОПЕЙСКАЯ РУЛЕТКА',768,560);board.body.itemSpacing=12;
const art=row(board.body,'Колесо и правила',728,258,24,'inset',0);art.primaryAxisAlignItems='CENTER';wheelArt(art,'roulette',258);const rule=frame(art,'Правила выплат',392,216,null,'VERTICAL',16,10);txt(rule,'37 чисел. Одна ставка.','Title');txt(rule,'Цвет / чётность    ×2','Mono','mint');txt(rule,'Одно число        ×36','Mono','gold');txt(rule,'Ноль — зелёный. Ставки на цвет и чётность при нуле проигрывают.','Small','muted',354);txt(rule,'Возврат в среднем: 97,3%','Caption','muted');
const grid=row(board.body,'Стол ставок',728,112,8);grid.counterAxisAlignItems='MIN';gameCell(grid,'0',44,112,'green');const numbers=frame(grid,'Числа 1–36',676,112,null,'VERTICAL',0,4);const red=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);for(let rowIndex=0;rowIndex<3;rowIndex++){const rr=row(numbers,'Числовой ряд '+rowIndex,676,34,4);for(let col=0;col<12;col++){const num=col*3+(3-rowIndex);gameCell(rr,String(num),52.33,34,red.has(num)?'red':'inset');}}
const recent=row(board.body,'Последние результаты',728,40,8);txt(recent,'ПОСЛЕДНИЕ','Caption','muted',96);for(const n of [17,8,0,23,31,14,2,19])gameCell(recent,String(n),44,34,n===0?'green':red.has(n)?'red':'inset');txt(board.body,'Прошлые результаты не меняют вероятность следующего вращения.','Caption','muted',720);
const stake=panel(game,'ВАША СТАВКА',376,560);stake.body.itemSpacing=10;txt(stake.body,'Доступно 1 240,50 монет','Small','gold');txt(stake.body,'Размер ставки','Small','muted');input(stake.body,'100',336);quickStake(stake.body);divider(stake.body,336);txt(stake.body,'Тип ставки','Label');const tabs=row(stake.body,'Тип',336,34,8);button(tabs,'Цвет',96,'Pressed',null,34);button(tabs,'Чётность',112,'Secondary',null,34);button(tabs,'Число',112,'Secondary',null,34);const colors=row(stake.body,'Выбор цвета',336,44,12);button(colors,'Красное',162,'Secondary');button(colors,'Чёрное',162,'Pressed');txt(stake.body,'Шанс: 18/37 ≈ 48,6%','Small','muted');const pay=frame(stake.body,'Ожидаемая выплата',336,68,'inset','VERTICAL',8,2);txt(pay,'При выигрыше','Caption','muted');txt(pay,'200,00  /  ×2','Title','gold');button(stake.body,'Крутить · 100 монет',336,'Primary');
gameFooter(content,'Выбрано: чёрное','При выигрыше вернётся 200 монет, чистая прибыль составит 100. Ноль проигрывает для этой ставки.');}
{
const {root,content}=await shell('wheel','games','Колесо фортуны','Выберите ставку — и дайте колесу решить.','← Все игры');route(root.findOne(n=>n.name==='Название раздела').children.at(-1),'games');screens.push(root);
const game=row(content,'Колесо и ставка',1168,560,24);const board=panel(game,'ПЯТЬ ВОЗМОЖНЫХ ИСХОДОВ',768,560);board.body.counterAxisAlignItems='CENTER';board.body.itemSpacing=12;const ar=row(board.body,'Иллюстрация колеса',728,340,0,'inset');ar.primaryAxisAlignItems='CENTER';wheelArt(ar,'wheel',340);const legend=row(board.body,'Множители',728,44,12);for(const [label,col] of [['×0 · 50%','raised'],['×1 · 30%','green'],['×2 · 15%','blue'],['×5 · 4%','gold'],['×15 · 1%','red']]){const b=frame(legend,'Исход '+label,136,44,col,'HORIZONTAL');b.primaryAxisAlignItems='CENTER';b.counterAxisAlignItems='CENTER';txt(b,label,'Small',col==='gold'||col==='red'?'ink':'text');}txt(board.body,'Размеры секторов соответствуют вероятностям.','Small','muted');
const stake=panel(game,'СТАВКА И ВЫПЛАТЫ',376,560);stake.body.itemSpacing=8;txt(stake.body,'Размер ставки · доступно 1 240,50','Small','muted');input(stake.body,'100',336);quickStake(stake.body);divider(stake.body,336);txt(stake.body,'Все исходы при ставке 100','Label');table(stake.body,[['Шанс',106],['Исход',82],['Выплата',124]],[['50%','×0','0,00'],['30%','×1','100,00'],['15%','×2','200,00'],['4%','×5','500,00'],['1%','×15','1 500,00']],336,{height:28,colors:['muted','text','gold']});button(stake.body,'Крутить · 100 монет',336,'Primary');txt(stake.body,'Средний возврат ставки: 95%.','Caption','muted');
gameFooter(content,'Одна ставка — одно вращение','×0: ставка не возвращается. ×1: возвращается ставка. ×2, ×5 и ×15: возвращается ставка с выигрышем.');}
{
const {root,content}=await shell('tower','games','Башня','Выше этаж — больше выигрыш. Можно остановиться в любой момент.','← Все игры');route(root.findOne(n=>n.name==='Название раздела').children.at(-1),'games');screens.push(root);
const game=row(content,'Башня и управление',1168,560,24);const board=panel(game,'ПРОЙДЕНО 3 ИЗ 8 ЭТАЖЕЙ',768,560);board.body.itemSpacing=4;board.body.paddingTop=12;board.body.paddingBottom=12;txt(board.body,'Выберите клетку четвёртого этажа','Small','mint');space(board.body,728,6);for(let level=8;level>=1;level--){const r=row(board.body,'Этаж '+level,728,46,10,level===4?'blue':null,4);txt(r,String(level).padStart(2,'0')+' этаж','Small','muted',82);for(let col=1;col<=4;col++){const chosen=level<=3&&col===[2,4,1][level-1];gameCell(r,chosen?'✓':level>4?'—':'?',112,38,chosen?'green':level===4?'raised':'inset');}txt(r,'×'+(.95/Math.pow(.75,level)).toFixed(2).replace('.',','),'Mono',level===4?'gold':'muted');}space(board.body,728,4);txt(board.body,'На каждом этаже: 3 безопасные клетки и 1 проигрышная.','Caption','muted');
const st=panel(game,'ТЕКУЩИЙ РАУНД',376,560);st.body.itemSpacing=10;txt(st.body,'Можно забрать','Caption','muted');txt(st.body,'225,18','Metric','gold');txt(st.body,'Чистая прибыль: +125,18 монет','Small','mint');button(st.body,'Забрать 225,18',336,'Primary');divider(st.body,336);const details=frame(st.body,'Данные раунда',336,112,'inset','VERTICAL',12,6);txt(details,'Ставка              100,00','Mono');txt(details,'Пройдено            3 / 8','Mono');txt(details,'Следующий этаж      ×3,00','Mono','mint');txt(st.body,'Доступно: 1 140,50 монет','Small','muted');txt(st.body,'100 монет зарезервировано в этом раунде и учитывается в рейтинге.','Small','muted',332);badge(st.body,'Автозабор через 12:43',232);txt(st.body,'При выборе опасной клетки выплата равна нулю.','Caption','muted',332);
gameFooter(content,'Продолжить или забрать?','Следующая безопасная клетка увеличит выплату до 300,24 монет. На 8-м этаже выигрыш забирается автоматически.');}
return audit(screens);
