await Promise.all([{family:'PT Sans',style:'Regular'},{family:'PT Sans',style:'Bold'},{family:'IBM Plex Mono',style:'Regular'},{family:'IBM Plex Mono',style:'Medium'},{family:'IBM Plex Mono',style:'Bold'}].map(f=>figma.loadFontAsync(f)));
const ids=[],mutated=[],links=[];
const keep=n=>(ids.push(n.id),n);
const entries=await Promise.all(Object.entries(state.tokens).map(async([k,id])=>[k,await figma.variables.getVariableByIdAsync(id)]));const V=Object.fromEntries(entries);
const C=Object.fromEntries(await Promise.all(Object.entries(state.components).map(async([k,id])=>[k,await figma.getNodeByIdAsync(id)])));
const I=Object.fromEntries(await Promise.all(Object.entries(state.icons).map(async([k,id])=>[k,await figma.getNodeByIdAsync(id)])));
const paint=k=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',V[k]);
function token(n,field,x){if(V['s'+x])n.setBoundVariable(field,V['s'+x]);else n[field]=x;}
function padding(n,p){for(const field of ['paddingTop','paddingRight','paddingBottom','paddingLeft'])token(n,field,p);}
function frame(p,name,w,h,color='panel',dir='VERTICAL',pad=0,gap=0){const n=keep(figma.createAutoLayout(dir));p.appendChild(n);n.name=name;n.resize(w,h);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';n.fills=color?[paint(color)]:[];padding(n,pad);token(n,'itemSpacing',gap);return n;}
function rect(p,x,y,w,h,color){const r=keep(figma.createRectangle());p.appendChild(r);if(p.layoutMode&&p.layoutMode!=='NONE')r.layoutPositioning='ABSOLUTE';r.x=x;r.y=y;r.resize(w,h);r.fills=[paint(color)];return r;}
function bevel(n,sunken=false){const w=n.width,h=n.height;const hi=sunken?'shadow':'edge',lo=sunken?'edge':'shadow';const t=rect(n,0,0,w,1,hi);t.constraints={horizontal:'STRETCH',vertical:'MIN'};const l=rect(n,0,0,1,h,hi);l.constraints={horizontal:'MIN',vertical:'STRETCH'};const b=rect(n,0,h-2,w,2,lo);b.constraints={horizontal:'STRETCH',vertical:'MAX'};const r=rect(n,w-2,0,2,h,lo);r.constraints={horizontal:'MAX',vertical:'STRETCH'};}
function txt(p,value,style='Body',color='text',w=null){const n=keep(figma.createText());p.appendChild(n);n.name=value.slice(0,50);n.textStyleId=state.styles[style];n.characters=value;n.fills=[paint(color)];n.textAutoResize='WIDTH_AND_HEIGHT';if(w){n.textAutoResize='HEIGHT';n.resize(w,20);}return n;}
function row(p,name,w,h,gap=12,color=null,pad=0){const n=frame(p,name,w,h,color,'HORIZONTAL',pad,gap);n.counterAxisAlignItems='CENTER';return n;}
function space(p,w,h=1){return frame(p,'Промежуток',w,h,null);}
function fill(n){n.layoutSizingHorizontal='FILL';return n;}
function prop(inst,key,val){const k=Object.keys(inst.componentProperties).find(k=>k.split('#')[0]===key);if(k)inst.setProperties({[k]:val});}
function route(n,target){n.name='Перейти / '+target;links.push({id:n.id,target});return n;}
function instance(p,c,w,h){const n=keep(c.createInstance());p.appendChild(n);if(w&&h)n.resize(w,h);return n;}
function button(p,label,w=208,kind='Primary',target=null,h=44){const n=instance(p,C['button'+kind],w,h);prop(n,'Label',label);if(target)route(n,target);return n;}
function input(p,value,w=320){const n=instance(p,C.input,w,48);prop(n,'Value',value);return n;}
function icon(p,key,size=28){return instance(p,I[key],size,size);}
function badge(p,label,w=152){const n=instance(p,C.badge,w,28);prop(n,'Label',label);return n;}
function panel(p,name,w,h){const n=frame(p,name,w,h,'panel');bevel(n);const bar=row(n,'Заголовок / '+name,w,34,8,'blue',8);txt(bar,name,'Label');const body=frame(n,'Содержимое / '+name,w,h-34,'panel','VERTICAL',20,12);return {root:n,body,bar};}
function metric(p,label,value,note,w=278){const c=figma.currentPage.findOne(n=>n.type==='COMPONENT'&&n.name==='Metric');const n=instance(p,c,w,110);prop(n,'Label',label);prop(n,'Value',value);prop(n,'Note',note);return n;}
function table(p,cols,rows,w,opts={}){const header=row(p,'Заголовки таблицы',w,30,0,'inset',12);cols.forEach(([label,cw])=>txt(header,label,'Caption','muted',cw));rows.forEach((values,i)=>{const r=row(p,'Строка '+(i+1),w,opts.height||36,0,i===opts.highlight?'blue':i%2?'raised':'panel',12);values.forEach((value,j)=>txt(r,value,opts.mono?'Mono':'Small',opts.colors?.[j]||'text',cols[j][1]));});}
function progress(p,w,count=20,completed=16){const r=row(p,'Сегментный индикатор',w,14,3,'inset',3);for(let i=0;i<count;i++){frame(r,'Сегмент '+(i+1),(w-6-(count-1)*3)/count,8,i<completed?'mint':'raised');}return r;}
function divider(p,w){return frame(p,'Разделитель',w,1,'edge');}
function heading(p,title,subtitle,tag=null){const r=row(p,'Название раздела',1168,66,24);const v=frame(r,'Заголовок',840,66,null,'VERTICAL',0,4);txt(v,title,'Heading');txt(v,subtitle,'Small','muted');if(tag){space(r,88);badge(r,tag,168);}return r;}
async function shell(key,active,title,subtitle,tag){const root=await figma.getNodeByIdAsync(state.roots[key]);if(root.children.length)throw new Error('Screen already populated: '+key);mutated.push(root.id);root.placeholder=false;
const top=row(root,'Шапка приложения',1440,76,16,'silver',24);icon(top,'coin',36);const brand=frame(top,'Бренд',260,52,null,'VERTICAL',0,0);txt(brand,'Focus Coins','Title','ink');txt(brand,'ВРЕМЯ, КОТОРОЕ ОСТАЁТСЯ','Caption','ink');space(top,578);badge(top,'●  Синхронизировано',166);const user=button(top,'pixel_anna',164,'Secondary','profile');
const main=row(root,'Рабочая область',1440,846,0);main.counterAxisAlignItems='MIN';const side=frame(main,'Навигация',208,846,'panel','VERTICAL',12,8);txt(side,'МОЙ ФОКУС','Caption','muted');space(side,184,8);
for(const [routeKey,label,ic] of [['timer','Таймер','timer'],['stats','Статистика','stats'],['games','Игры','games'],['rating','Рейтинг','rank'],['profile','Профиль','profile']]){const n=instance(side,C[active===routeKey?'navActive':'navDefault'],184,48);prop(n,'Label',label);prop(n,'Icon',I[ic].id);route(n,routeKey);}
space(side,184,248);const wallet=frame(side,'Кошелёк',184,106,'inset','VERTICAL',12,4);bevel(wallet,true);txt(wallet,'БАЛАНС СЕЗОНА','Caption','muted');const wr=row(wallet,'Баланс',160,38,6);icon(wr,'coin',22);txt(wr,key==='complete'?'1 290,50':'1 240,50','Title','gold');txt(wallet,'Виртуальные монеты','Caption','muted');
const season=frame(side,'Текущий сезон',184,98,null,'VERTICAL',8,4);txt(season,'Октябрь 2026','Label');txt(season,'Место  № 42','Small','mint');txt(season,'До нового сезона: 24 дня','Caption','muted');
const content=frame(main,'Основное содержимое',1232,846,null,'VERTICAL',32,20);heading(content,title,subtitle,tag);
const status=row(root,'Статус приложения',1440,38,16,'inset',12);txt(status,'● Онлайн','Caption','mint');divider(status,1);txt(status,'Сезон: октябрь 2026','Caption','muted');space(status,842);txt(status,'Asia/Yekaterinburg · UTC+5','Caption','muted');return {root,content};}
function dayCycle(p,w=328,complete=false){const r=row(p,'Семь дней',w,62,8);for(let i=1;i<=7;i++){const n=frame(r,'День '+i,40,62,i<4||(complete&&i===4)?'green':i===4?'blue':'inset','VERTICAL',4,0);bevel(n,i===4);n.counterAxisAlignItems='CENTER';txt(n,i<4||(complete&&i===4)?'✓':String(i),'Label',i===7?'gold':'text');txt(n,['+10','+15','+20','+25','+30','+40','+50'][i-1],'Caption',i===7?'gold':'muted');}return r;}
function miniStat(p,label,value,w=160){const n=frame(p,label,w,62,'inset','VERTICAL',8,2);bevel(n,true);txt(n,label,'Caption','muted');txt(n,value,'Title');return n;}
function svg(p,name,markup,w,h){const n=keep(figma.createNodeFromSvg('<svg width="'+w+'" height="'+h+'" viewBox="0 0 '+w+' '+h+'" xmlns="http://www.w3.org/2000/svg">'+markup+'</svg>'));p.appendChild(n);n.name=name;return n;}
function audit(roots){const all=roots.flatMap(n=>[n,...n.findAll(()=>true)]);const counts={};for(const n of all)counts[n.type]=(counts[n.type]||0)+1;const fonts=[...new Set(all.filter(n=>n.type==='TEXT').map(n=>typeof n.fontName==='object'?n.fontName.family:'mixed'))];const images=all.filter(n=>Array.isArray(n.fills)&&n.fills.some(f=>f.type==='IMAGE')).map(n=>({id:n.id,name:n.name,type:n.type,width:n.width,height:n.height}));return {allCreatedNodeIds:[...new Set([...ids,...all.map(n=>n.id)])],mutatedNodeIds:mutated,links,counts,fonts,images,rootBounds:roots.map(n=>({id:n.id,name:n.name,width:n.width,height:n.height}))};}
function wheelArt(p,kind,size){const cx=size/2,cy=size/2,r=size*.42;let s='<rect width="'+size+'" height="'+size+'" fill="#101D24"/>';const pieces=kind==='wheel'?[{v:.5,c:'#51626D'},{v:.3,c:'#9EE7C5'},{v:.15,c:'#356BCD'},{v:.04,c:'#F4CF70'},{v:.01,c:'#ED9992'}]:Array.from({length:37},(_,i)=>({v:1/37,c:i===0?'#236649':i%2?'#B74A48':'#25323C'}));let a=-Math.PI/2;for(const seg of pieces){const b=a+seg.v*Math.PI*2;const x=cx+r*Math.cos(a),y=cy+r*Math.sin(a),ex=cx+r*Math.cos(b),ey=cy+r*Math.sin(b);s+='<path d="M'+cx+' '+cy+'L'+x.toFixed(3)+' '+y.toFixed(3)+'A'+r+' '+r+' 0 '+(seg.v>.5?1:0)+' 1 '+ex.toFixed(3)+' '+ey.toFixed(3)+'Z" fill="'+seg.c+'" stroke="#101D24" stroke-width="3"/>';a=b;}s+='<circle cx="'+cx+'" cy="'+cy+'" r="'+r+'" fill="none" stroke="#7D909C" stroke-width="3"/><circle cx="'+cx+'" cy="'+cy+'" r="'+size*.13+'" fill="#C3CBCD" stroke="#09131C" stroke-width="3"/><path d="M'+(cx-12)+' 5H'+(cx+12)+'L'+cx+' 28Z" fill="#F4CF70"/>';return svg(p,kind==='wheel'?'Колесо / вероятность':'Рулетка / 37 секторов',s,size,size);}
