await Promise.all([{family:'PT Sans',style:'Regular'},{family:'PT Sans',style:'Bold'},{family:'IBM Plex Mono',style:'Regular'},{family:'IBM Plex Mono',style:'Medium'},{family:'IBM Plex Mono',style:'Bold'}].map(f=>figma.loadFontAsync(f)));
const page=figma.currentPage; page.name='Focus Coins · Макеты';
const ids=[]; const keep=n=>(ids.push(n.id),n);
const rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const palette={bg:'#18232C',panel:'#2C3943',raised:'#3B4A55',inset:'#101D24',silver:'#C3CBCD',ink:'#14232B',text:'#F0F3EB',muted:'#ACBAC1',edge:'#7D909C',shadow:'#09131C',blue:'#12388E',bright:'#356BCD',mint:'#9EE7C5',gold:'#F4CF70',red:'#ED9992',green:'#236649'};
const primitive=figma.variables.createVariableCollection('FC / Primitives'); primitive.renameMode(primitive.modes[0].modeId,'Default');
const tokens=figma.variables.createVariableCollection('FC / UI'); tokens.renameMode(tokens.modes[0].modeId,'Dark');
const vars={};
for(const [name,hex] of Object.entries(palette)){
 const p=figma.variables.createVariable(name,primitive,'COLOR');p.scopes=[];p.setValueForMode(primitive.modes[0].modeId,rgb(hex));p.setVariableCodeSyntax('WEB','var(--fc-'+name+'-raw)');
 const v=figma.variables.createVariable('color/'+name,tokens,'COLOR');v.scopes=['FRAME_FILL','SHAPE_FILL','TEXT_FILL','STROKE_COLOR','EFFECT_COLOR'];v.setValueForMode(tokens.modes[0].modeId,{type:'VARIABLE_ALIAS',id:p.id});v.setVariableCodeSyntax('WEB','var(--fc-'+name+')');vars[name]=v;
}
for(const x of [0,4,8,12,16,20,24,32,40]){const v=figma.variables.createVariable('space/'+x,tokens,'FLOAT');v.scopes=['GAP'];v.setValueForMode(tokens.modes[0].modeId,x);v.setVariableCodeSyntax('WEB','var(--fc-space-'+x+')');vars['s'+x]=v;}
const radius=figma.variables.createVariable('radius/square',tokens,'FLOAT');radius.scopes=['CORNER_RADIUS'];radius.setValueForMode(tokens.modes[0].modeId,0);radius.setVariableCodeSyntax('WEB','var(--fc-radius-square)');
const paint=k=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb(palette[k])},'color',vars[k]);
const styles={};
for(const [name,size,font,weight,lh] of [['Body',16,'PT Sans','Regular',24],['Small',14,'PT Sans','Regular',20],['Caption',12,'PT Sans','Regular',18],['Label',16,'PT Sans','Bold',22],['Heading',30,'PT Sans','Bold',38],['Title',22,'PT Sans','Bold',28],['Mono',14,'IBM Plex Mono','Regular',22],['Metric',32,'IBM Plex Mono','Medium',42],['Timer',100,'IBM Plex Mono','Medium',120]]){const s=figma.createTextStyle();s.name='FC / '+name;s.fontName={family:font,style:weight};s.fontSize=size;s.lineHeight={unit:'PIXELS',value:lh};styles[name]=s;}
function text(parent,value,style='Body',color='text'){const n=keep(figma.createText());parent.appendChild(n);n.textStyleId=styles[style].id;n.characters=value;n.fills=[paint(color)];n.textAutoResize='WIDTH_AND_HEIGHT';n.name=value.slice(0,50);return n;}
function box(parent,name,w,h,fill='panel',dir='VERTICAL'){const n=keep(figma.createAutoLayout(dir));parent.appendChild(n);n.name=name;n.resize(w,h);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';n.fills=fill?[paint(fill)]:[];return n;}
function rect(parent,x,y,w,h,fill){const r=keep(figma.createRectangle());parent.appendChild(r);if(parent.layoutMode&&parent.layoutMode!=='NONE')r.layoutPositioning='ABSOLUTE';r.x=x;r.y=y;r.resize(w,h);r.fills=[paint(fill)];return r;}
function bevel(n,inset=false){const hi=inset?'shadow':'edge',lo=inset?'edge':'shadow';const w=n.width,h=n.height;const a=rect(n,0,0,w,1,hi);a.constraints={horizontal:'STRETCH',vertical:'MIN'};const b=rect(n,0,0,1,h,hi);b.constraints={horizontal:'MIN',vertical:'STRETCH'};const c=rect(n,0,h-2,w,2,lo);c.constraints={horizontal:'STRETCH',vertical:'MAX'};const d=rect(n,w-2,0,2,h,lo);d.constraints={horizontal:'MAX',vertical:'STRETCH'};}
const lib=box(page,'UI Kit · исходные компоненты',1360,650,null);lib.x=100;lib.y=-850;lib.layoutMode='NONE';
const iconSVG={
 coin:'<path d="M6 2h12v2h4v4h2v12h-2v4h-4v2H6v-2H2v-4H0V8h2V4h4z" fill="#8B641F"/><path d="M6 4h12v2h4v14h-4v4H6v-4H2V6h4z" fill="#F4CF70"/><path d="M8 6h10v2H8v2H6v10H4V8h4z" fill="#FFF1B2"/><path d="M14 8h-4v3H8v8h2v2h4v-2h3v-2h-5v-4h5v-2h-3z" fill="#AD7B26"/>',
 timer:'<path d="M8 1h8v3H8zM4 6h16v3h3v14h-3v3H4v-3H1V9h3z" fill="#9EE7C5"/><path d="M6 9h12v3h2v8h-2v3H6v-3H4v-8h2z" fill="#14232B"/><path d="M11 10h3v7h5v3h-8z" fill="#9EE7C5"/>',
 stats:'<path d="M2 20h5v6H2zM10 12h5v14h-5zM18 3h5v23h-5z" fill="#9EE7C5"/>',
 games:'<path d="M2 4h20v20H2z" fill="#F4CF70"/><path d="M6 8h4v4H6zM14 8h4v4h-4zM10 12h4v4h-4zM6 16h4v4H6zM14 16h4v4h-4z" fill="#14232B"/>',
 rank:'<path d="M6 2h12v4h5v9h-4v3h-4v4h4v4H5v-4h4v-4H5v-3H1V6h5zm0 7H4v4h2zm12 0v4h2V9z" fill="#F4CF70"/>',
 profile:'<path d="M8 2h8v2h3v9h-3v3H8v-3H5V4h3zM5 18h14v3h4v5H1v-5h4z" fill="#C3CBCD"/>',
 check:'<path d="M2 12h4v4h4v-4h4V8h4V4h4v8h-4v4h-4v4h-4v4H6v-4H2z" fill="#9EE7C5"/>',
 play:'<path d="M5 2h4v3h4v3h4v3h4v4h-4v3h-4v3H9v3H5z" fill="#F0F3EB"/>',
 tower:'<path d="M2 2h5v5h4V2h5v5h4V2h4v9h-2v15H4V11H2z" fill="#9EE7C5"/><path d="M10 18h6v8h-6zM7 11h4v4H7zM15 11h4v4h-4z" fill="#14232B"/>'};
const icons={};let ix=0;
for(const [name,svg] of Object.entries(iconSVG)){const c=keep(figma.createComponent());lib.appendChild(c);c.name='Icon / '+name;c.resize(28,28);c.x=24+ix*60;c.y=36;c.fills=[];c.description='Пиксельная иконка на сетке 2 px.';const v=keep(figma.createNodeFromSvg('<svg width="26" height="28" viewBox="0 0 26 28" xmlns="http://www.w3.org/2000/svg">'+svg+'</svg>'));c.appendChild(v);icons[name]=c;ix++;}
const comps={};
for(const kind of ['Primary','Secondary','Pressed','Disabled']){const c=keep(figma.createComponent());lib.appendChild(c);c.name='State='+kind;c.resize(208,44);c.layoutMode='HORIZONTAL';c.primaryAxisAlignItems='CENTER';c.counterAxisAlignItems='CENTER';c.fills=[paint(kind==='Primary'?'blue':kind==='Pressed'?'inset':kind==='Disabled'?'raised':'silver')];bevel(c,kind==='Pressed');const t=text(c,'Начать сессию','Label',kind==='Secondary'?'ink':kind==='Disabled'?'muted':'text');t.componentPropertyReferences={characters:c.addComponentProperty('Label','TEXT','Начать сессию')};comps['button'+kind]=c;}
const bs=keep(figma.combineAsVariants(Object.values(comps),lib));bs.name='Button';bs.description='Основное действие, вторичное действие, нажатое и недоступное состояния. Прямоугольная кнопка с двухпиксельным рельефом.';bs.x=24;bs.y=110;bs.children.forEach((v,i)=>{v.x=i*228;v.y=0;});bs.resize(900,64);
for(const active of [false,true]){const c=keep(figma.createComponent());lib.appendChild(c);c.name='Active='+active;c.resize(184,48);c.layoutMode='HORIZONTAL';c.paddingLeft=16;c.itemSpacing=12;c.counterAxisAlignItems='CENTER';c.fills=[paint(active?'blue':'raised')];bevel(c,active);const ic=keep(icons.timer.createInstance());c.appendChild(ic);ic.componentPropertyReferences={mainComponent:c.addComponentProperty('Icon','INSTANCE_SWAP',icons.timer.id)};const t=text(c,'Таймер','Label');t.componentPropertyReferences={characters:c.addComponentProperty('Label','TEXT','Таймер')};comps[active?'navActive':'navDefault']=c;}
const ns=keep(figma.combineAsVariants([comps.navDefault,comps.navActive],lib));ns.name='Navigation';ns.description='Раздел приложения. Иконка заменяется через Instance Swap.';ns.x=24;ns.y=214;ns.children.forEach((v,i)=>{v.x=i*208;v.y=0;});ns.resize(400,68);
const input=keep(figma.createComponent());lib.appendChild(input);input.name='Input';input.resize(320,48);input.x=24;input.y=316;input.layoutMode='HORIZONTAL';input.counterAxisAlignItems='CENTER';input.paddingLeft=16;input.fills=[paint('inset')];bevel(input,true);const it=text(input,'25','Mono');it.componentPropertyReferences={characters:input.addComponentProperty('Value','TEXT','25')};comps.input=input;input.description='Утопленное поле. Value управляет отображаемым текстом.';
const badge=keep(figma.createComponent());lib.appendChild(badge);badge.name='Badge';badge.resize(152,28);badge.x=400;badge.y=316;badge.layoutMode='HORIZONTAL';badge.counterAxisAlignItems='CENTER';badge.primaryAxisAlignItems='CENTER';badge.fills=[paint('inset')];const bt=text(badge,'Синхронизировано','Caption','mint');bt.componentPropertyReferences={characters:badge.addComponentProperty('Label','TEXT','Синхронизировано')};comps.badge=badge;
const layouts=[['timer','01 · Таймер',1440,960,100,100],['running','02 · Сессия идёт',1440,960,1740,100],['complete','03 · Сессия завершена',1440,960,3380,100],['stats','04 · Статистика',1440,960,100,1240],['games','05 · Игры',1440,960,1740,1240],['roulette','06 · Рулетка',1440,960,3380,1240],['wheel','07 · Колесо фортуны',1440,960,100,2380],['tower','08 · Башня',1440,960,1740,2380],['rating','09 · Рейтинг',1440,960,3380,2380],['profile','10 · Профиль',1440,960,100,3520],['login','11 · Вход',1440,960,1740,3520],['mobileTimer','12 · Mobile / Таймер',390,844,100,4800],['mobileGames','13 · Mobile / Игры',390,844,650,4800],['mobileRating','14 · Mobile / Рейтинг',390,844,1200,4800]];
const roots={};for(const [key,name,w,h,x,y] of layouts){const f=box(page,name,w,h,'bg');f.x=x;f.y=y;f.itemSpacing=0;f.placeholder=true;roots[key]=f.id;}
text(lib,'FOCUS COINS / UI 2000','Title').set({x:24,y:430});text(lib,'Квадратная геометрия · рельефные границы · утопленные поля · русский интерфейс','Small','muted').set({x:24,y:474});text(lib,'PT Sans — интерфейс / IBM Plex Mono — цифры','Small','muted').set({x:24,y:508});
return {createdNodeIds:ids,mutatedNodeIds:[page.id],collections:[primitive.id,tokens.id],tokens:Object.fromEntries(Object.entries(vars).map(([k,v])=>[k,v.id])),styles:Object.fromEntries(Object.entries(styles).map(([k,v])=>[k,v.id])),components:Object.fromEntries(Object.entries(comps).map(([k,v])=>[k,v.id])),icons:Object.fromEntries(Object.entries(icons).map(([k,v])=>[k,v.id])),roots,kit:lib.id,rootBounds:layouts.map(l=>({name:l[1],width:l[2],height:l[3]}))};
