await Promise.all([{family:'PT Sans',style:'Regular'},{family:'PT Sans',style:'Bold'},{family:'IBM Plex Mono',style:'Regular'},{family:'IBM Plex Mono',style:'Medium'},{family:'IBM Plex Mono',style:'Bold'}].map(f=>figma.loadFontAsync(f)));
const ids=[],mutated=[],rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const coll=await figma.variables.getVariableCollectionByIdAsync(state.collections[1]);const primitive=await figma.variables.getVariableCollectionByIdAsync(state.collections[0]);const dark=coll.modes[0].modeId;const light=coll.modes.find(m=>m.name==='Light')?.modeId||coll.addMode('Light');
const raw=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).filter(v=>v.variableCollectionId===primitive.id).map(v=>[v.name,v]));
const lightColors={bg:'#ECE9E2',panel:'#D4D0C8',raised:'#E2DFD7',inset:'#F7F7F0',silver:'#D4D0C8',ink:'#17232E',text:'#17232E',muted:'#505A62',edge:'#FFFFFF',shadow:'#767970',blue:'#12388E',bright:'#356BCD',mint:'#166850',gold:'#7B570D',red:'#E5A49D',green:'#BFD4BF'};
const vars=Object.fromEntries(await Promise.all(Object.entries(state.tokens).map(async([k,id])=>[k,await figma.variables.getVariableByIdAsync(id)])));
for(const [k,h] of Object.entries(lightColors)){let p=raw['Light/'+k];if(!p){p=figma.variables.createVariable('Light/'+k,primitive,'COLOR');p.scopes=[];p.setValueForMode(primitive.modes[0].modeId,rgb(h));p.setVariableCodeSyntax('WEB','var(--fc-light-'+k+'-raw)');}vars[k].setValueForMode(light,{type:'VARIABLE_ALIAS',id:p.id});}
for(const [k,h,lh] of [['onBlue','#F0F3EB','#FFFFFF'],['rouletteBlack','#25323C','#25323C'],['rouletteRed','#B74A48','#B74A48'],['rouletteGreen','#236649','#236649'],['iconNeutral','#C3CBCD','#2B3C53']]){const p=figma.variables.createVariable(k,primitive,'COLOR');p.scopes=[];p.setValueForMode(primitive.modes[0].modeId,rgb(h));p.setVariableCodeSyntax('WEB','var(--fc-'+k+'-raw)');const pl=figma.variables.createVariable('Light/'+k,primitive,'COLOR');pl.scopes=[];pl.setValueForMode(primitive.modes[0].modeId,rgb(lh));pl.setVariableCodeSyntax('WEB','var(--fc-light-'+k+'-raw)');const v=figma.variables.createVariable('color/'+k,coll,'COLOR');v.scopes=['FRAME_FILL','SHAPE_FILL','TEXT_FILL','STROKE_COLOR'];v.setValueForMode(dark,{type:'VARIABLE_ALIAS',id:p.id});v.setValueForMode(light,{type:'VARIABLE_ALIAS',id:pl.id});v.setVariableCodeSyntax('WEB','var(--fc-'+k+')');vars[k]=v;}
const paint=k=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb('#000000')},'color',vars[k]);
function background(n){let p=n.parent;while(p&&p.type!=='PAGE'){if(Array.isArray(p.fills)&&p.fills.length){const a=p.fills.find(f=>f.type==='SOLID'&&f.visible!==false&&f.opacity!==0);if(a)return a.boundVariables?.color?.id;}p=p.parent;}return null;}
// Canonical repairs from layout bounds audit.
const preset=await figma.getNodeByIdAsync('3:160');preset.resize(720,48);mutated.push(preset.id);
for(const id of ['7:518']){const n=await figma.getNodeByIdAsync(id);n.resize(1128,32);mutated.push(n.id);}const ops=await figma.getNodeByIdAsync('7:497');for(const r of ops.children.filter(n=>n.name.startsWith('Строка '))){r.resize(1128,32);mutated.push(r.id);}
const tools=await figma.getNodeByIdAsync('7:963');tools.resize(1128,48);mutated.push(tools.id);
const device=await figma.getNodeByIdAsync('7:1257');for(const n of device.children.filter(n=>n.name==='Веб'||n.name==='Телефон')){n.resize(528,40);mutated.push(n.id);}const logout=await figma.getNodeByIdAsync('7:1270');logout.resize(220,36);mutated.push(logout.id);
const roulette=await figma.getNodeByIdAsync(state.roots.roulette);const boardAreas=roulette.findAll(n=>n.type==='FRAME'&&(n.name==='Стол ставок'||n.name==='Последние результаты'));for(const ar of boardAreas){for(const n of ar.findAllWithCriteria({types:['INSTANCE']})){if(n.mainComponent?.name!=='Game Cell')continue;const id=n.fills[0]?.boundVariables?.color?.id;n.fills=[paint(id===vars.red.id?'rouletteRed':id===vars.green.id?'rouletteGreen':'rouletteBlack')];for(const t of n.findAllWithCriteria({types:['TEXT']})){t.fills=[paint('onBlue')];mutated.push(t.id);}mutated.push(n.id);}}
const roots=await Promise.all(Object.values(state.roots).map(id=>figma.getNodeByIdAsync(id)));const kit=await figma.getNodeByIdAsync(state.kit);
for(const root of [...roots,kit]){for(const t of root.findAllWithCriteria({types:['TEXT']})){const bg=background(t);if(bg===vars.blue.id){t.fills=[paint('onBlue')];mutated.push(t.id);}}}
// Theme the monochrome profile icon and preserve selected-icon contrast.
for(const root of [...roots,kit]){for(const v of root.findAllWithCriteria({types:['VECTOR']})){let p=v.parent,inIcon=false,coin=false;while(p&&p.type!=='PAGE'){if(p.name==='Icon / profile'){inIcon=true;break;}if(p.name==='Icon / coin'){coin=true;break;}p=p.parent;}if(inIcon&&!coin){v.fills=v.fills.map(f=>f.type==='SOLID'?paint(background(v)===vars.blue.id?'onBlue':'iconNeutral'):f);mutated.push(v.id);}}}
const lightPage=figma.createPage();lightPage.name='02 · Светлая тема';ids.push(lightPage.id);const cloned={};
for(const [key,id] of Object.entries(state.roots)){const source=await figma.getNodeByIdAsync(id);const clone=source.clone();lightPage.appendChild(clone);clone.x=source.x;clone.y=source.y;clone.setExplicitVariableModeForCollection(coll,light);clone.name=source.name+' · Light';cloned[key]=clone.id;ids.push(clone.id,...clone.findAll(()=>true).map(n=>n.id));}
const darkPage=figma.currentPage;darkPage.name='01 · Тёмная тема';mutated.push(darkPage.id);
await figma.setCurrentPageAsync(lightPage);
const profile=await figma.getNodeByIdAsync(cloned.profile);const theme=profile.findOne(n=>n.name==='Тема');const primary=await figma.getNodeByIdAsync(state.components.buttonPressed),secondary=await figma.getNodeByIdAsync(state.components.buttonSecondary);for(const n of theme.children.filter(n=>n.type==='INSTANCE')){const label=Object.values(n.componentProperties).find(p=>p.type==='TEXT')?.value;const labelKey=Object.keys(n.componentProperties).find(k=>k.startsWith('Label'));n.swapComponent(label==='Светлая'?primary:secondary);const propKey=Object.keys(n.componentProperties).find(k=>k.startsWith('Label'));n.setProperties({[propKey]:label});n.resize(180,44);mutated.push(n.id);}
const texts=Object.values(cloned).flatMap(id=>{const r=lightPage.children.find(n=>n.id===id);return r.findAllWithCriteria({types:['TEXT']});});const fonts=[...new Set(texts.map(t=>typeof t.fontName==='object'?t.fontName.family:'mixed'))];
figma.viewport.scrollAndZoomIntoView([await figma.getNodeByIdAsync(cloned.timer)]);
return {createdNodeIds:ids,mutatedNodeIds:mutated,lightPage:lightPage.id,darkPage:darkPage.id,lightMode:light,darkMode:dark,lightRoots:cloned,tokens:Object.fromEntries(Object.entries(vars).map(([k,v])=>[k,v.id])),fontFamilies:fonts,clonedScreenCount:Object.keys(cloned).length,textCount:texts.length};
