const kit=await figma.getNodeByIdAsync(state.kit);
if(!figma.currentPage.findOne(n=>n.type==='COMPONENT'&&n.name==='Metric')){const c=keep(figma.createComponent());kit.appendChild(c);c.name='Metric';c.description='Ключевой показатель: подпись, число, контекст.';c.resize(278,110);c.x=24;c.y=570;c.layoutMode='VERTICAL';padding(c,12);c.itemSpacing=0;c.fills=[paint('panel')];bevel(c);for(const [key,value,style,color] of [['Label','Концентрация','Caption','muted'],['Value','10 ч 20 м','Metric','text'],['Note','За текущий сезон','Caption','muted']]){const t=txt(c,value,style,color);t.componentPropertyReferences={characters:c.addComponentProperty(key,'TEXT',value)};}}
const screens=[];
for(const [key,mode] of [['timer','idle'],['running','active'],['complete','done']]){
const {root,content}=await shell(key,'timer',mode==='active'?'Время для главного':mode==='done'?'Хорошая работа. Время сохранено.':'Время для главного',mode==='done'?'Сессия закончилась. Монеты уже в кошельке.':'Одна задача. Один таймер. Каждая минута приносит монету.','07 октября · среда');screens.push(root);
const upper=row(content,'Таймер и награды',1168,464,24);upper.counterAxisAlignItems='MIN';const focus=panel(upper,'КОНЦЕНТРАЦИЯ',768,464);const p=focus.body;p.paddingTop=20;p.paddingBottom=20;p.paddingLeft=24;p.paddingRight=24;p.itemSpacing=14;
const display=frame(p,'Дисплей таймера',720,202,'inset','VERTICAL',12,0);bevel(display,true);display.counterAxisAlignItems='CENTER';txt(display,mode==='active'?'СЕССИЯ ИДЁТ':mode==='done'?'СЕССИЯ ЗАВЕРШЕНА':'ГОТОВЫ НАЧАТЬ?','Caption','mint');txt(display,mode==='active'?'21:43':mode==='done'?'00:00':'25:00','Timer',mode==='done'?'gold':'mint');txt(display,mode==='active'?'14:00 → 14:25  /  25 минут':mode==='done'?'+25 монет за концентрацию':'25 минут концентрации = 25 монет','Mono','muted');
if(mode==='active'){progress(p,720,28,4);const a=row(p,'Управление активной сессией',720,44,16);button(a,'Отменить сессию',248,'Secondary','timer');txt(a,'При отмене монеты не начисляются','Small','muted');const info=row(p,'Продолжение на устройствах',720,48,12,'raised',12);icon(info,'check',22);txt(info,'Таймер продолжит идти после закрытия приложения.','Small');txt(p,'Начисление произойдёт автоматически в 14:25.','Caption','muted');}
else if(mode==='done'){const bonus=row(p,'Начислено',720,52,16,'green',12);icon(bonus,'coin',24);txt(bonus,'+25 ежедневный бонус · 4-й день серии','Label');const a=row(p,'Следующее действие',720,44,12);button(a,'Ещё 25 минут',248,'Primary','running');button(a,'Посмотреть статистику',240,'Secondary','stats');txt(p,'Суммарно сегодня: 45 минут. Ежедневная цель выполнена.','Small','muted');}
else{const presets=row(p,'Длительность',720,44,8);txt(presets,'Минуты','Small','muted',72);button(presets,'25',72,'Pressed');button(presets,'50',72,'Secondary');button(presets,'90',72,'Secondary');input(presets,'25',140);txt(presets,'от 1 до 360','Caption','muted');const a=row(p,'Старт',720,44,16);button(a,'Начать сессию',304,'Primary','running');icon(a,'coin',22);txt(a,'Будет начислено 25 монет','Small','gold');txt(p,'Достаточно выбрать задачу и не отвлекаться.','Small','muted');}
const right=frame(upper,'Награды',376,464,null,'VERTICAL',0,20);const daily=panel(right,'ЕЖЕДНЕВНАЯ ЦЕЛЬ',376,300);const d=daily.body;txt(d,mode==='done'?'4 дня подряд':'3 дня подряд','Metric');txt(d,mode==='done'?'Сегодня: 45 / 25 минут':'Сегодня: 20 / 25 минут','Small','muted');progress(d,336,20,mode==='done'?20:16);dayCycle(d,328,mode==='done');txt(d,mode==='done'?'Бонус +25 начислен автоматически.':'Ещё 5 минут → бонус +25 монет','Small',mode==='done'?'mint':'gold');txt(d,'День учитывается по времени окончания сессии.','Caption','muted',332);
const extra=panel(right,'СЕДЬМОЙ ДЕНЬ',376,144);const er=row(extra.body,'Усиление',336,42,12);icon(er,'coin',32);const ec=frame(er,'Описание',280,42,null,'VERTICAL',0,0);txt(ec,'+50 монет и усиление ×1,5','Label','gold');txt(ec,'24 часа · только для новых сессий','Caption','muted');txt(extra.body,'Продолжайте серию — осталось 3 дня.','Small','muted');
const history=panel(content,'ПОСЛЕДНИЕ СЕССИИ',1168,208);history.body.paddingTop=8;history.body.paddingBottom=8;history.body.itemSpacing=0;
table(history.body,[['Дата',300],['Длительность',300],['Статус',300],['Монеты',216]],mode==='done'?[['Сегодня, 14:25','25 мин','Завершена','+25'],['Сегодня, 13:20','10 мин','Завершена','+10'],['Сегодня, 10:50','10 мин','Завершена','+10']]:[['Сегодня, 13:20','10 мин','Завершена','+10'],['Сегодня, 10:50','10 мин','Завершена','+10'],['Вчера, 18:40','35 мин','Завершена','+35']],1128,{colors:['muted','text','mint','gold']});
const foot=row(history.body,'Правило',1128,22,0);txt(foot,'1 минута = 1 монета. Отмена сессии не приносит монет.','Caption','muted');
}
return audit(screens);
